title: Introduction to Artificial Chemisties
description: Introduction to Artificial Chemisties, Universidad Nacional de Colombia 2017-2
sitename: Artificial Chemisties Course 2017
baseurl: '/ac-course-2017'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
